name: Android CI

on:
  push:
    branches: [ "master" ] 

jobs:
  My_testing:

    runs-on: ubuntu-latest

    steps:
    - name: Testing
      run: echo "Hello word "
    
    - name: Git clone my repository
      uses: actions/checkout@v1
      
    - name: List my repo
      run: ls -la
   
    
    
